### ISSUE TITLE
Time and Date doesn't detect `ntp`.

### ISSUE THREAD

**Issue by flexiondotorg** [mate-desktop-legacy-archive/mate-system-tools#12]
Hi,

On Arch Linux running MATE 1.6 with `ntp` installed and `ntpd` enabled via `systemd`, the Time and Date tool from `mate-system-tools` doesn't detect that NTP is available.

Therefore, it is not possible to set the Time and Date configuration to `Keep synchronised with Internet servers.`

Regards, Martin.

**Comment by stefano-k** [comment]
Closing.
mate-system-tools will be removed in 1.10
