### ISSUE TITLE
Shared Folders doesn't detect Samba or NFS

### ISSUE THREAD

**Issue by flexiondotorg** [mate-desktop-legacy-archive/mate-system-tools#13]
Hi,

On Arch Linux running MATE 1.6 with `samba` installed and enabled via `systemd`. `nfs-utils` is also installed with `rpc.imapd`, `rpc.statd`, `rpc.bind` and `rpc.mountd` enabled and running via `systemd`.

The Shared Folders tool from `mate-system-tools` doesn't detect Samba or NFS, therefore, it is not possible to add/edit any shared resources.

Regards, Martin.

**Comment by stefano-k** [comment]
Closing.
mate-system-tools will be removed in 1.10
