### ISSUE TITLE
Services tool is not compatible with `systemd`.

### ISSUE THREAD

**Issue by flexiondotorg** [mate-desktop-legacy-archive/mate-system-tools#14]
Hi,

On Arch Linux running MATE 1.6 and `systemd` the Services tool doesn't disaply anything when launched.

Please can the Services tool be made compatible with `systemd`?

Regards, Martin.

**Comment by infirit** [comment]
That is because system-tools-backends does not support systemd. The last commit is from 3 years ago, http://cgit.freedesktop.org/system-tools-backends/, so I would not get my hope up :)

**Comment by stefano-k** [comment]
Closing.
mate-system-tools will be removed in 1.10
