### ISSUE TITLE
Full name changes are not saved

### ISSUE THREAD

**Issue by Zero3** [mate-desktop-legacy-archive/mate-system-tools#23]
Distribution: Linux Mint 17 Qiana

The 'change' feature for a user's full name under System -> Administration -> Users and Groups (mate-users-admin) doesn't work. The name is changed in the GUI but is not properly saved. This can be verified by closing and re-opening the dialog which then shows the old name.

**Comment by monsta** [comment]
I confirm this.
Also when you run mate-users-admin from the terminal, two warning messages appear:

```
monsta@mint17 ~ $ mate-users-admin 

(mate-users-admin:2247): Liboobs-WARNING **: There was an unknown error communicating asynchronously with the backends: Launch helper exited with unknown return code 255

(mate-users-admin:2247): Liboobs-WARNING **: There was an unknown error communicating with the backends: Launch helper exited with unknown return code 255
```

The first one is printed right after starting the app, the second one is printed when you've changed your full name and clicked on the button to save the changes.

Here's some stuff from /var/log/syslog as well.
This is after mate-users-admin starting:

```
Sep 15 15:11:42 mint17 dbus[453]: [system] Activating service name='org.freedesktop.SystemToolsBackends.UsersConfig2' (using servicehelper)
Sep 15 15:11:42 mint17 dbus[453]: [system] Activating service name='org.freedesktop.SystemToolsBackends.GroupsConfig2' (using servicehelper)
Sep 15 15:11:43 mint17 dbus[453]: [system] Activating service name='org.freedesktop.SystemToolsBackends.SelfConfig2' (using servicehelper)
Sep 15 15:11:43 mint17 dbus[453]: [system] Activated service 'org.freedesktop.SystemToolsBackends.SelfConfig2' failed: Launch helper exited with unknown return code 255
Sep 15 15:11:44 mint17 dbus[453]: [system] Successfully activated service 'org.freedesktop.SystemToolsBackends.UsersConfig2'
Sep 15 15:11:44 mint17 dbus[453]: [system] Successfully activated service 'org.freedesktop.SystemToolsBackends.GroupsConfig2'
```

This is after pushing the button to save the full name changes:

```
Sep 15 15:12:27 mint17 dbus[453]: [system] Activating service name='org.freedesktop.SystemToolsBackends.SelfConfig2' (using servicehelper)
Sep 15 15:12:27 mint17 dbus[453]: [system] Activated service 'org.freedesktop.SystemToolsBackends.SelfConfig2' failed: Launch helper exited with unknown return code 255
```

**Comment by monsta** [comment]
I think this should be fixed now in Mint 17.1 Rebecca. The fix is complex: I had to make changes not only to mate-system-tools, but also to its backends - liboobs and system-tools-backends.

**Comment by monsta** [comment]
@Zero3: if it works for you in Mint 17.1, you can close this issue.

**Comment by Zero3** [comment]
Seems to work now - thanks! :)
