### ISSUE TITLE
HACKING file is really outdated?

### ISSUE THREAD

**Issue by oz123** [mate-desktop-legacy-archive/mate-system-tools#28]
I am trying to hack mate-system-tools, the file HACKING states there should be a directory called `backend`:

```
Breakdown of the tools currently packaged:

Backend                          Frontend              Frontend layout
-------                          --------              ---------------
backend/disks-conf.in           src/disks/*           interfaces/disks.glade
backend/memory-conf.in          src/memory/*          interfaces/memory.glade
backend/nameresolution-conf.in  src/nameresolution/*  interfaces/nameresolution.glade
backend/networking-conf.in      src/networking/*      interfaces/networking.glade
backend/shares-conf.in          src/shares/*          interfaces/shares.glade
backend/time-conf.in            src/time/*            interfaces/time.glade
backend/users-conf.in           src/users/*           interfaces/users.glade

Currently, all the backends are in Perl, all the frontends are in C, and all
the frontend layouts are in Glade XML. We accept backends and frontends in
Python, though.

There are also common libraries in these three categories:

backend/be.pl          - shared Perl code.
src/common/*            - shared C code.
interfaces/common.glade - shared Glade specifications.
```

It seems to me that all functionality is in C inside the `src/` directory. 
However, if the package real just depends on system-tools-backends-2.0, that should be mentioned in the HACKING file.

**Comment by monsta** [comment]
Ah, it's not important, this project will be dropped in 1.10 anyway. :)

**Comment by oz123** [comment]
@monsta, 
what is going to replace this?

**Comment by monsta** [comment]
Not sure, `gnome-system-tools` probably (though they're not maintained upstream anymore) or distro-specific tools (like `system-config-*` tools in Fedora). Better ask @stefano-k...

**Comment by oz123** [comment]
hmm ... I am smelling bad news. All those tools in gnome-system-tools where pearl modules. 
Maybe we can replace that with readable python code?

**Comment by monsta** [comment]
Well, mate-system-tools is a fork of gnome-system-tools, it uses the same two backends (liboobs and system-tools-backends). The backends are out of our scope, they're not MATE-specific.

**Comment by Lesik** [comment]
That is horrible news. Now there is not a single cross-plattform. Fedora has its tools, but they're not available anywhere else. Both `gnome-system-tools` and `mate-system-tools` have been dropped.

That is really sad.
