### ISSUE TITLE
Shares not work 

### ISSUE THREAD

**Issue by Frannoe** [mate-desktop-legacy-archive/mate-system-tools#3]
Shares  (NFS y Samba) not work if it is removed gnome-system-tools.
Is this correct?
mate-system-tools does not replace gnome-system-tools?

Regards

**Comment by szesch** [comment]
http://forums.mate-desktop.org/viewtopic.php?f=6&t=147

That thread suggests installing the gvfs-backends package.

**Comment by Frannoe** [comment]
I'll go see this possible solution
Thank you very much

Edit: This package is installed by default.
The process does not work if we remove gnome-system-tools
Thank

**Comment by szesch** [comment]
How are you attempting to access the shares?

**Comment by Frannoe** [comment]
Still not working , the process does not work if we remove gnome-system-tools

**Comment by szesch** [comment]
...That didn't answer my question. How are you attempting to access the shares? Please list the steps.

**Comment by Frannoe** [comment]
I do not follow any particular step.
I use MATE. Logically I want to use the MATE package.
But erasing gnome-system-tools folder sharing does not work.
The package mate-system-tools does not perform well this particular service
Nothing happens when pressing to share folder

**Comment by Frannoe** [comment]
Well, I've accomplished something.
Renaming the package usr/bin/mate-shares-admin 
to 
shares-admin
It seems to work correctly.
This then seems more a problem of Caja is not it?
would have to rename all the other packages?:
mate-time-admin, mate-users-admin, mate-network-admin, etc.
this is not good, and would break compatibility between desktops.

**Comment by szesch** [comment]
Fixed https://github.com/mate-desktop/mate-system-tools/commit/ca2fe4848f13cfcec6f1fac20edf1f6da514d8a4

Available in mate-system-tools-1.2.3-1.
