### ISSUE TITLE
mate-network-admin gets confused by multiple entries with the same ip

### ISSUE THREAD

**Issue by leo-unglaub** [mate-desktop-legacy-archive/mate-system-tools#5]
Hey,
if you use the mate-network-admin to modify the /etc/hosts file you can get the following bug. The mate-network-admin tool loads all items with the same IP into the same field. But thats not very useful.
- It gets really hard to read.
- Some items are missing after that.

```
Example:
127.0.0.1 foobar.org www.foobar.orrg
127.0.0.1 site.dev www.site.dev
```

The tool puts everything together into one entry based on the ip but it would make much more sence if it would group them line by line and not by ip address.

Thanks and greetings
Leo

**Comment by stefano-k** [comment]
Closing.
mate-system-tools will be removed in 1.10
