### ISSUE TITLE
Settings user as administrator account type and still can't install/etc...

### ISSUE THREAD

**Issue by amireldor** [mate-desktop-legacy-archive/mate-system-tools#8]
(Not sure if this is the right repository to report the issue)

When creating a new user and assigning him as an administrator, the user is not added to the "sudo" group and thus cannot destroy the world (e.g. install new software, create other users, etc...).

Reproduce (what happened to me at least):
1. User alice installed Mint 14 with the MATE desktop
2. User alice created the user cooper from the admin settings GUI
3. User alice assigned the account type of cooper to "administrator"
4. User cooper was happy
5. User cooper logged in with his new password successfully
6. User cooper opened the software manager, the password prompt popped up
7. User cooper entered his password and whoops! 403

I don't remember if the password prompt did show up or whether it just gave a restriced access message, but it doesn't matter much.

With some help from IRC, we discovered that cooper did not belong to the "sudo" group. Once alice added cooper with `usermod +aG sudo cooper`, cooper was granted access to destroying the universe.

**Comment by flexiondotorg** [comment]
Confirmed.

**Comment by infirit** [comment]
From what I can see this is distribution specific. For example in Fedora and Gentoo this is handled differently and does not have a sudo group.

I would suggest to ask the maintainer to patch the following file and add the necessary groups. 

```
https://github.com/mate-desktop/mate-system-tools/blob/master/src/users/user-profiles.conf.in
```

**Comment by flexiondotorg** [comment]
Yep, I found the same and will patch it for Arch Linux.

**Comment by flexiondotorg** [comment]
This is fixed in Arch Linux via packaging.

@stefano-k - Suggest this is closed. @infirit is correct this issue is distribution specific.

**Comment by stefano-k** [comment]
@flexiondotorg @infirit maybe we could add a note on README before close the issue?

**Comment by infirit** [comment]
@stefano-k sure, this is reasonable I think.

```
- For Distributors:

  Distributions may want to modify src/users/user-profiles.conf.in and add
  groups that are specific to that distribution. For example add the sudo
  group for Administrators on ubuntu based distributions.
```

**Comment by stefano-k** [comment]
Hehe, next time I will as to one person only :-D
